name: "Deploy"
description: "Deploy to Rede Linux"
inputs:
  username:
    description: "Rede Linux username"
    required: true
  password:
    description: "Rede Linux password"
    required: true
runs:
  using: "composite"
  steps:
    - name: Pre-Deploy
      run: ./.github/scripts/pre-deploy.sh
      shell: bash
    - name: Update monografia.pdf
      uses: appleboy/scp-action@master
      with:
        host: linux.ime.usp.br
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        source: "monografia.pdf"
        target: "~/www/mac0499"
        overwrite: true